/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UploadsRouteImport } from './routes/uploads'
import { Route as ExportsExportIdRouteImport } from './routes/exports/$exportId'
import { Route as ImportsIndexRouteImport } from './routes/imports/index'
import { Route as ImportsImportIdRouteImport } from './routes/imports/$importId'
import { Route as SettingsCategoriesRouteImport } from './routes/settings_.categories'
import { Route as SettingsRulesRouteImport } from './routes/settings_.rules'
import { Route as SettingsSuggestionsRouteImport } from './routes/settings_.suggestions'
import { Route as SourcesSourceFileIdRouteImport } from './routes/sources/$sourceFileId'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as TransactionsIdRouteImport } from './routes/transactions/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsRoute = UploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsExportIdRoute = ExportsExportIdRouteImport.update({
  id: '/exports/$exportId',
  path: '/exports/$exportId',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsIndexRoute = ImportsIndexRouteImport.update({
  id: '/imports/',
  path: '/imports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsImportIdRoute = ImportsImportIdRouteImport.update({
  id: '/imports/$importId',
  path: '/imports/$importId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCategoriesRoute = SettingsCategoriesRouteImport.update({
  id: '/settings_/categories',
  path: '/settings/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRulesRoute = SettingsRulesRouteImport.update({
  id: '/settings_/rules',
  path: '/settings/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSuggestionsRoute = SettingsSuggestionsRouteImport.update({
  id: '/settings_/suggestions',
  path: '/settings/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesSourceFileIdRoute = SourcesSourceFileIdRouteImport.update({
  id: '/sources/$sourceFileId',
  path: '/sources/$sourceFileId',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIdRoute = TransactionsIdRouteImport.update({
  id: '/transactions/$id',
  path: '/transactions/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/uploads': typeof UploadsRoute
  '/exports/$exportId': typeof ExportsExportIdRoute
  '/imports/$importId': typeof ImportsImportIdRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/rules': typeof SettingsRulesRoute
  '/settings/suggestions': typeof SettingsSuggestionsRoute
  '/sources/$sourceFileId': typeof SourcesSourceFileIdRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/imports/': typeof ImportsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/uploads': typeof UploadsRoute
  '/exports/$exportId': typeof ExportsExportIdRoute
  '/imports/$importId': typeof ImportsImportIdRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/rules': typeof SettingsRulesRoute
  '/settings/suggestions': typeof SettingsSuggestionsRoute
  '/sources/$sourceFileId': typeof SourcesSourceFileIdRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/imports': typeof ImportsIndexRoute
  '/transactions': typeof TransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/uploads': typeof UploadsRoute
  '/exports/$exportId': typeof ExportsExportIdRoute
  '/imports/$importId': typeof ImportsImportIdRoute
  '/settings_/categories': typeof SettingsCategoriesRoute
  '/settings_/rules': typeof SettingsRulesRoute
  '/settings_/suggestions': typeof SettingsSuggestionsRoute
  '/sources/$sourceFileId': typeof SourcesSourceFileIdRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/imports/': typeof ImportsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/overview'
    | '/review'
    | '/settings'
    | '/uploads'
    | '/exports/$exportId'
    | '/imports/$importId'
    | '/settings/categories'
    | '/settings/rules'
    | '/settings/suggestions'
    | '/sources/$sourceFileId'
    | '/transactions/$id'
    | '/imports/'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/overview'
    | '/review'
    | '/settings'
    | '/uploads'
    | '/exports/$exportId'
    | '/imports/$importId'
    | '/settings/categories'
    | '/settings/rules'
    | '/settings/suggestions'
    | '/sources/$sourceFileId'
    | '/transactions/$id'
    | '/imports'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/overview'
    | '/review'
    | '/settings'
    | '/uploads'
    | '/exports/$exportId'
    | '/imports/$importId'
    | '/settings_/categories'
    | '/settings_/rules'
    | '/settings_/suggestions'
    | '/sources/$sourceFileId'
    | '/transactions/$id'
    | '/imports/'
    | '/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OverviewRoute: typeof OverviewRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  UploadsRoute: typeof UploadsRoute
  ExportsExportIdRoute: typeof ExportsExportIdRoute
  ImportsImportIdRoute: typeof ImportsImportIdRoute
  SettingsCategoriesRoute: typeof SettingsCategoriesRoute
  SettingsRulesRoute: typeof SettingsRulesRoute
  SettingsSuggestionsRoute: typeof SettingsSuggestionsRoute
  SourcesSourceFileIdRoute: typeof SourcesSourceFileIdRoute
  TransactionsIdRoute: typeof TransactionsIdRoute
  ImportsIndexRoute: typeof ImportsIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads': {
      id: '/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof UploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports/$exportId': {
      id: '/exports/$exportId'
      path: '/exports/$exportId'
      fullPath: '/exports/$exportId'
      preLoaderRoute: typeof ExportsExportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports/': {
      id: '/imports/'
      path: '/imports'
      fullPath: '/imports/'
      preLoaderRoute: typeof ImportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports/$importId': {
      id: '/imports/$importId'
      path: '/imports/$importId'
      fullPath: '/imports/$importId'
      preLoaderRoute: typeof ImportsImportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/categories': {
      id: '/settings_/categories'
      path: '/settings/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof SettingsCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/rules': {
      id: '/settings_/rules'
      path: '/settings/rules'
      fullPath: '/settings/rules'
      preLoaderRoute: typeof SettingsRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/suggestions': {
      id: '/settings_/suggestions'
      path: '/settings/suggestions'
      fullPath: '/settings/suggestions'
      preLoaderRoute: typeof SettingsSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$sourceFileId': {
      id: '/sources/$sourceFileId'
      path: '/sources/$sourceFileId'
      fullPath: '/sources/$sourceFileId'
      preLoaderRoute: typeof SourcesSourceFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/$id': {
      id: '/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof TransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OverviewRoute: OverviewRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  UploadsRoute: UploadsRoute,
  ExportsExportIdRoute: ExportsExportIdRoute,
  ImportsImportIdRoute: ImportsImportIdRoute,
  SettingsCategoriesRoute: SettingsCategoriesRoute,
  SettingsRulesRoute: SettingsRulesRoute,
  SettingsSuggestionsRoute: SettingsSuggestionsRoute,
  SourcesSourceFileIdRoute: SourcesSourceFileIdRoute,
  TransactionsIdRoute: TransactionsIdRoute,
  ImportsIndexRoute: ImportsIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
