/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalystRouteRouteImport } from './routes/analyst/route'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SpendingRouteImport } from './routes/spending'
import { Route as UploadsRouteImport } from './routes/uploads'
import { Route as AnalystIndexRouteImport } from './routes/analyst/index'
import { Route as AnalystConversationIdRouteImport } from './routes/analyst/$conversationId'
import { Route as CounterpartiesIndexRouteImport } from './routes/counterparties/index'
import { Route as CounterpartiesCounterpartyIdRouteImport } from './routes/counterparties/$counterpartyId'
import { Route as ExportsExportIdRouteImport } from './routes/exports/$exportId'
import { Route as LedgerIndexRouteImport } from './routes/ledger/index'
import { Route as LedgerIdRouteImport } from './routes/ledger/$id'
import { Route as SettingsCategoriesRouteImport } from './routes/settings_.categories'
import { Route as SettingsRulesRouteImport } from './routes/settings_.rules'
import { Route as SourcesIndexRouteImport } from './routes/sources/index'
import { Route as SourcesSourceFileIdRouteImport } from './routes/sources/$sourceFileId'
import { Route as SourcesImportsImportIdRouteImport } from './routes/sources/imports/$importId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystRouteRoute = AnalystRouteRouteImport.update({
  id: '/analyst',
  path: '/analyst',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SpendingRoute = SpendingRouteImport.update({
  id: '/spending',
  path: '/spending',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsRoute = UploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystIndexRoute = AnalystIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalystRouteRoute,
} as any)
const AnalystConversationIdRoute = AnalystConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => AnalystRouteRoute,
} as any)
const CounterpartiesIndexRoute = CounterpartiesIndexRouteImport.update({
  id: '/counterparties/',
  path: '/counterparties/',
  getParentRoute: () => rootRouteImport,
} as any)
const CounterpartiesCounterpartyIdRoute =
  CounterpartiesCounterpartyIdRouteImport.update({
    id: '/counterparties/$counterpartyId',
    path: '/counterparties/$counterpartyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExportsExportIdRoute = ExportsExportIdRouteImport.update({
  id: '/exports/$exportId',
  path: '/exports/$exportId',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerIndexRoute = LedgerIndexRouteImport.update({
  id: '/ledger/',
  path: '/ledger/',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerIdRoute = LedgerIdRouteImport.update({
  id: '/ledger/$id',
  path: '/ledger/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCategoriesRoute = SettingsCategoriesRouteImport.update({
  id: '/settings_/categories',
  path: '/settings/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRulesRoute = SettingsRulesRouteImport.update({
  id: '/settings_/rules',
  path: '/settings/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesSourceFileIdRoute = SourcesSourceFileIdRouteImport.update({
  id: '/sources/$sourceFileId',
  path: '/sources/$sourceFileId',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesImportsImportIdRoute = SourcesImportsImportIdRouteImport.update({
  id: '/sources/imports/$importId',
  path: '/sources/imports/$importId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyst': typeof AnalystRouteRouteWithChildren
  '/questions': typeof QuestionsRoute
  '/settings': typeof SettingsRoute
  '/spending': typeof SpendingRoute
  '/uploads': typeof UploadsRoute
  '/analyst/$conversationId': typeof AnalystConversationIdRoute
  '/counterparties/$counterpartyId': typeof CounterpartiesCounterpartyIdRoute
  '/exports/$exportId': typeof ExportsExportIdRoute
  '/ledger/$id': typeof LedgerIdRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/rules': typeof SettingsRulesRoute
  '/sources/$sourceFileId': typeof SourcesSourceFileIdRoute
  '/analyst/': typeof AnalystIndexRoute
  '/counterparties/': typeof CounterpartiesIndexRoute
  '/ledger/': typeof LedgerIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/sources/imports/$importId': typeof SourcesImportsImportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/questions': typeof QuestionsRoute
  '/settings': typeof SettingsRoute
  '/spending': typeof SpendingRoute
  '/uploads': typeof UploadsRoute
  '/analyst/$conversationId': typeof AnalystConversationIdRoute
  '/counterparties/$counterpartyId': typeof CounterpartiesCounterpartyIdRoute
  '/exports/$exportId': typeof ExportsExportIdRoute
  '/ledger/$id': typeof LedgerIdRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/rules': typeof SettingsRulesRoute
  '/sources/$sourceFileId': typeof SourcesSourceFileIdRoute
  '/analyst': typeof AnalystIndexRoute
  '/counterparties': typeof CounterpartiesIndexRoute
  '/ledger': typeof LedgerIndexRoute
  '/sources': typeof SourcesIndexRoute
  '/sources/imports/$importId': typeof SourcesImportsImportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyst': typeof AnalystRouteRouteWithChildren
  '/questions': typeof QuestionsRoute
  '/settings': typeof SettingsRoute
  '/spending': typeof SpendingRoute
  '/uploads': typeof UploadsRoute
  '/analyst/$conversationId': typeof AnalystConversationIdRoute
  '/counterparties/$counterpartyId': typeof CounterpartiesCounterpartyIdRoute
  '/exports/$exportId': typeof ExportsExportIdRoute
  '/ledger/$id': typeof LedgerIdRoute
  '/settings_/categories': typeof SettingsCategoriesRoute
  '/settings_/rules': typeof SettingsRulesRoute
  '/sources/$sourceFileId': typeof SourcesSourceFileIdRoute
  '/analyst/': typeof AnalystIndexRoute
  '/counterparties/': typeof CounterpartiesIndexRoute
  '/ledger/': typeof LedgerIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/sources/imports/$importId': typeof SourcesImportsImportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyst'
    | '/questions'
    | '/settings'
    | '/spending'
    | '/uploads'
    | '/analyst/$conversationId'
    | '/counterparties/$counterpartyId'
    | '/exports/$exportId'
    | '/ledger/$id'
    | '/settings/categories'
    | '/settings/rules'
    | '/sources/$sourceFileId'
    | '/analyst/'
    | '/counterparties/'
    | '/ledger/'
    | '/sources/'
    | '/sources/imports/$importId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/questions'
    | '/settings'
    | '/spending'
    | '/uploads'
    | '/analyst/$conversationId'
    | '/counterparties/$counterpartyId'
    | '/exports/$exportId'
    | '/ledger/$id'
    | '/settings/categories'
    | '/settings/rules'
    | '/sources/$sourceFileId'
    | '/analyst'
    | '/counterparties'
    | '/ledger'
    | '/sources'
    | '/sources/imports/$importId'
  id:
    | '__root__'
    | '/'
    | '/analyst'
    | '/questions'
    | '/settings'
    | '/spending'
    | '/uploads'
    | '/analyst/$conversationId'
    | '/counterparties/$counterpartyId'
    | '/exports/$exportId'
    | '/ledger/$id'
    | '/settings_/categories'
    | '/settings_/rules'
    | '/sources/$sourceFileId'
    | '/analyst/'
    | '/counterparties/'
    | '/ledger/'
    | '/sources/'
    | '/sources/imports/$importId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalystRouteRoute: typeof AnalystRouteRouteWithChildren
  QuestionsRoute: typeof QuestionsRoute
  SettingsRoute: typeof SettingsRoute
  SpendingRoute: typeof SpendingRoute
  UploadsRoute: typeof UploadsRoute
  CounterpartiesCounterpartyIdRoute: typeof CounterpartiesCounterpartyIdRoute
  ExportsExportIdRoute: typeof ExportsExportIdRoute
  LedgerIdRoute: typeof LedgerIdRoute
  SettingsCategoriesRoute: typeof SettingsCategoriesRoute
  SettingsRulesRoute: typeof SettingsRulesRoute
  SourcesSourceFileIdRoute: typeof SourcesSourceFileIdRoute
  CounterpartiesIndexRoute: typeof CounterpartiesIndexRoute
  LedgerIndexRoute: typeof LedgerIndexRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
  SourcesImportsImportIdRoute: typeof SourcesImportsImportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyst': {
      id: '/analyst'
      path: '/analyst'
      fullPath: '/analyst'
      preLoaderRoute: typeof AnalystRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spending': {
      id: '/spending'
      path: '/spending'
      fullPath: '/spending'
      preLoaderRoute: typeof SpendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads': {
      id: '/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof UploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyst/': {
      id: '/analyst/'
      path: '/'
      fullPath: '/analyst/'
      preLoaderRoute: typeof AnalystIndexRouteImport
      parentRoute: typeof AnalystRouteRoute
    }
    '/analyst/$conversationId': {
      id: '/analyst/$conversationId'
      path: '/$conversationId'
      fullPath: '/analyst/$conversationId'
      preLoaderRoute: typeof AnalystConversationIdRouteImport
      parentRoute: typeof AnalystRouteRoute
    }
    '/counterparties/': {
      id: '/counterparties/'
      path: '/counterparties'
      fullPath: '/counterparties/'
      preLoaderRoute: typeof CounterpartiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counterparties/$counterpartyId': {
      id: '/counterparties/$counterpartyId'
      path: '/counterparties/$counterpartyId'
      fullPath: '/counterparties/$counterpartyId'
      preLoaderRoute: typeof CounterpartiesCounterpartyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports/$exportId': {
      id: '/exports/$exportId'
      path: '/exports/$exportId'
      fullPath: '/exports/$exportId'
      preLoaderRoute: typeof ExportsExportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger/': {
      id: '/ledger/'
      path: '/ledger'
      fullPath: '/ledger/'
      preLoaderRoute: typeof LedgerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger/$id': {
      id: '/ledger/$id'
      path: '/ledger/$id'
      fullPath: '/ledger/$id'
      preLoaderRoute: typeof LedgerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/categories': {
      id: '/settings_/categories'
      path: '/settings/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof SettingsCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/rules': {
      id: '/settings_/rules'
      path: '/settings/rules'
      fullPath: '/settings/rules'
      preLoaderRoute: typeof SettingsRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/': {
      id: '/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$sourceFileId': {
      id: '/sources/$sourceFileId'
      path: '/sources/$sourceFileId'
      fullPath: '/sources/$sourceFileId'
      preLoaderRoute: typeof SourcesSourceFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/imports/$importId': {
      id: '/sources/imports/$importId'
      path: '/sources/imports/$importId'
      fullPath: '/sources/imports/$importId'
      preLoaderRoute: typeof SourcesImportsImportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AnalystRouteRouteChildren {
  AnalystConversationIdRoute: typeof AnalystConversationIdRoute
  AnalystIndexRoute: typeof AnalystIndexRoute
}

const AnalystRouteRouteChildren: AnalystRouteRouteChildren = {
  AnalystConversationIdRoute: AnalystConversationIdRoute,
  AnalystIndexRoute: AnalystIndexRoute,
}

const AnalystRouteRouteWithChildren = AnalystRouteRoute._addFileChildren(
  AnalystRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalystRouteRoute: AnalystRouteRouteWithChildren,
  QuestionsRoute: QuestionsRoute,
  SettingsRoute: SettingsRoute,
  SpendingRoute: SpendingRoute,
  UploadsRoute: UploadsRoute,
  CounterpartiesCounterpartyIdRoute: CounterpartiesCounterpartyIdRoute,
  ExportsExportIdRoute: ExportsExportIdRoute,
  LedgerIdRoute: LedgerIdRoute,
  SettingsCategoriesRoute: SettingsCategoriesRoute,
  SettingsRulesRoute: SettingsRulesRoute,
  SourcesSourceFileIdRoute: SourcesSourceFileIdRoute,
  CounterpartiesIndexRoute: CounterpartiesIndexRoute,
  LedgerIndexRoute: LedgerIndexRoute,
  SourcesIndexRoute: SourcesIndexRoute,
  SourcesImportsImportIdRoute: SourcesImportsImportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
